name: run unit tests on feature branch

on:
 push:
   branches: 
     'feature/*'
jobs:
 run-unit-tests:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v3.3.0
     
   - name: run unit test
     uses: mvn test

  
    
  
  
   
    
